IRRELEVANT_NAME    = 'irrelevant name'
OTHER_NAME         = 'other name'
IRRELEVANT_ID      = 'irrelevant id'
AGGREGATE_ID       = 'aggregate id'
IRRELEVANT_CHANGE1 = 'irrelevant change 1'
IRRELEVANT_CHANGE2 = 'irrelevant change 2'
IRRELEVANT_EVENT   = 'irrelevant event'
IRRELEVANT_VERSION = 'irrelevant version'
